-- ╔══════════════════════════════════════════════════════════════╗
-- ║  MedBot — Privacy-First Ingestion Pipeline                 ║
-- ║  Original PDFs are NEVER stored. Only redacted text.      ║
-- ║  Run this in Supabase SQL Editor                          ║
-- ╚══════════════════════════════════════════════════════════════╝

-- This migration is optional (schema already supports it)
-- The pipeline works WITHOUT any schema changes:
--
-- FLOW:
-- 1. Client extracts PDF text using PDF.js
-- 2. Client redacts PII using frontend regex patterns
-- 3. Client sends ONLY redacted text to backend
-- 4. Original PDF is immediately discarded (never stored)
-- 5. Backend redacts again (defense in depth, regex only)
-- 6. Backend validates redaction
-- 7. Backend stores only redacted text in chunks table
--
-- PRIVACY GUARANTEE:
-- Zero unredacted PII is ever transmitted to backend or stored in database.
-- All chunks contain [PATIENT_NAME], [DOB], [MRN], etc. — never real values.
--
-- STORAGE FOOTPRINT:
-- - Lightweight function size (no PyMuPDF, fpdf2)
-- - Stays well within Vercel free tier (250MB limit)
-- - Redacted text only (original PDF discarded on client)
--
-- DISPLAY:
-- - Chat left panel: styled monospace text (redacted report)
-- - No PDF rendering (unnecessary and privacy risk if original persisted)
